# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under roteiro_ds_01/resources/*
# and roteiro_ds_01/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for roteiro_ds_01 Prod

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./roteiro_ds_01

env:
  DATABRICKS_TOKEN: ${{ secrets.PROD_WORKSPACE_TOKEN }}

jobs:
  prod:
    concurrency: roteiro_ds_01-prod-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.236.0
      - name: Validate Bundle For Prod
        id: validate
        run: |
          databricks bundle validate -t prod
      - name: Deploy Bundle to Prod
        id: deploy
        run: |
          databricks bundle deploy -t prod
